/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vp;

import helper.database;
import helper.reset;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author YOGA
 */
public class dataDokter extends javax.swing.JFrame {
    private Connection conn = new database().connect(); //adjust to master branch
    private DefaultTableModel tabmode;
    database db = new database();
    reset rst = new reset();
    String[] columns = {"id_dokter","nama_dokter","tempat","tgl_lahir","jenis_kelamin","agama","spesialis","no_telp"};
    String[] columnsUpdate = {"nama_dokter","tempat","tgl_lahir","jenis_kelamin","agama","spesialis","no_telp"};

    /**
     * Creates new form dataDokter
     */
    public dataDokter() {
        initComponents();
        datatable();
    }
    
    //Adjust datatable method below to master branch
    protected void datatable(){
        Object[] Baris = {"ID Dokter","Nama Dokter","Tempat","Tanggal Lahir","Jenis Kelamin","Agama","Spesialis","No Telp"};
        tabmode = new DefaultTableModel(null, Baris);
        tDokter.setModel(tabmode);
        String sql = "SELECT * FROM dokter";
        try{
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                String a = hasil.getString("id_dokter");
                String b = hasil.getString("nama_dokter");
                String c = hasil.getString("tempat");
                String d = hasil.getString("tgl_lahir");
                String e = hasil.getString("jenis_kelamin");
                String f = hasil.getString("agama");
                String g = hasil.getString("spesialis");
                String h = hasil.getString("no_telp");
                String[] data={a,b,c,d,e,f,g,h};
                tabmode.addRow(data);
        }
        } catch (Exception e){
            e.printStackTrace();
        }
    }
    
    protected void aktif(){
        idDokter.setEnabled(true);
        namaDokter.setEnabled(true);
        tempatDokter.setEnabled(true);
        tanggalDokter.setEnabled(true);
        //jkDokter.setEnabled(true);
        //agamaDokter.setEnabled(true);
        //spesialisDokter.setEnabled(true);
        telpDokter.setEnabled(true);
        idDokter.requestFocus();
    }
    
    protected void kosong(){
        idDokter.setText("");
        namaDokter.setText("");
        tempatDokter.setText("");
        tanggalDokter.setDate(null);
        jkDokter.setSelectedItem(true);
        agamaDokter.setSelectedItem(true);
        spesialisDokter.setSelectedItem(true);
        telpDokter.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        idDokter = new javax.swing.JTextField();
        telpDokter = new javax.swing.JTextField();
        tempatDokter = new javax.swing.JTextField();
        jkDokter = new javax.swing.JComboBox<>();
        agamaDokter = new javax.swing.JComboBox<>();
        spesialisDokter = new javax.swing.JComboBox<>();
        namaDokter = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tDokter = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        tanggalDokter = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("ID Dokter");

        jLabel2.setText("Nama Dokter");

        jLabel3.setText("TTL");

        jLabel4.setText("Jenis Kelamin");

        jLabel6.setText("Agama");

        jLabel7.setText("Spesialis");

        jLabel8.setText("No. Telp");

        idDokter.setEnabled(false);
        idDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idDokterActionPerformed(evt);
            }
        });

        jkDokter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "== Pilih Jenis Kelamin == ", "Laki-Laki", "Perempuan" }));
        jkDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jkDokterActionPerformed(evt);
            }
        });

        agamaDokter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "== Pilih Agama==", "Islam", "Kristen", "Katolik", "Hindu", "Buddha", "Konghucu" }));

        spesialisDokter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "== Pilih Spesialis ==", "Dokter Umum", "Dokter Spesialis" }));
        spesialisDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spesialisDokterActionPerformed(evt);
            }
        });

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        tDokter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Dokter", "Nama Dokter", "TTL", "Umur", "Jenis Kelamin", "Agama", "Spesialis", "No Telp"
            }
        ));
        tDokter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tDokterMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tDokter);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("DATA DOKTER");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(save)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(edit)
                                .addGap(77, 77, 77)
                                .addComponent(delete))
                            .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(telpDokter)
                            .addComponent(idDokter)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tempatDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tanggalDokter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jkDokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(agamaDokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spesialisDokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namaDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(392, 392, 392)
                        .addComponent(jLabel9)))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(idDokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(namaDokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tempatDokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(tanggalDokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jkDokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(agamaDokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(spesialisDokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(telpDokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(save, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(delete)
                        .addComponent(edit)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(reset)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jkDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jkDokterActionPerformed
        
    }//GEN-LAST:event_jkDokterActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        kosong();
        datatable();
    }//GEN-LAST:event_resetActionPerformed

    private void spesialisDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spesialisDokterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spesialisDokterActionPerformed
    
    
    
    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        String nd = namaDokter.getText();
        String td = tempatDokter.getText();
        java.sql.Date tgld = new java.sql.Date(tanggalDokter.getDate().getTime());
        String jk = jkDokter.getSelectedItem().toString();
        String agd = agamaDokter.getSelectedItem().toString();
        String sp = spesialisDokter.getSelectedItem().toString();
        String telpd = telpDokter.getText();
        Object[] values = {"0",nd,td,tgld,jk,agd,sp,telpd};
        
        idDokter.requestFocus();
        try{
            if(jkDokter.getSelectedIndex() == 0  || agamaDokter.getSelectedIndex() == 0 || spesialisDokter.getSelectedIndex() == 0){
                JOptionPane.showMessageDialog(null, "Data masih ada yang belum dipilih.");
            }else{
                db.insertData(conn, "dokter", columns, values);
                datatable();
            }
            
        }catch(SQLException ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_saveActionPerformed
    void reset(){
        rst.resetTextFields(this.getContentPane());
    }
    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        String idDokter = this.idDokter.getText();
        String nd = namaDokter.getText();
        String td = tempatDokter.getText();
        java.sql.Date tgld = new java.sql.Date(tanggalDokter.getDate().getTime());
        String jk = jkDokter.getSelectedItem().toString();
        String agd = agamaDokter.getSelectedItem().toString();
        String sp = spesialisDokter.getSelectedItem().toString();
        String telpd = telpDokter.getText();
        Object[] values = {nd,td,tgld,jk,agd,sp,telpd};
        String condition = "id_dokter = " + idDokter; //
        System.out.println(condition);
        try {
            // Memanggil fungsi updateData
            db.updateData(conn, "dokter", columnsUpdate, values, condition);
            datatable();
            reset();
        } catch (SQLException ex) {
            Logger.getLogger(dataDokter.class.getName()).log(Level.SEVERE, null, ex);
        }                  
    }//GEN-LAST:event_editActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        int ok = JOptionPane.showConfirmDialog(null, "hapus","Konfirmasi Dialog", JOptionPane.YES_NO_CANCEL_OPTION);
        if (ok==0){
             int id_dokter = Integer.parseInt(idDokter.getText());
             try {
                String condition = "id_dokter = " + id_dokter;
                db.deleteData(conn, "dokter", condition);
                datatable();
                reset();
            } catch (SQLException ex) {
                Logger.getLogger(dataDokter.class.getName()).log(Level.SEVERE, null, ex);

            }
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void tDokterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tDokterMouseClicked
        int selectedRowIndex =  tDokter.getSelectedRow();
        String a = tabmode.getValueAt(selectedRowIndex, 0).toString();
        String b = tabmode.getValueAt(selectedRowIndex, 1).toString();
        String c = tabmode.getValueAt(selectedRowIndex, 2).toString();
        String d = tabmode.getValueAt(selectedRowIndex, 3).toString();
        String e = tabmode.getValueAt(selectedRowIndex, 4).toString();
        String f = tabmode.getValueAt(selectedRowIndex, 5).toString();
        String g = tabmode.getValueAt(selectedRowIndex, 6).toString();
        String h = tabmode.getValueAt(selectedRowIndex, 7).toString();
        idDokter.setText(a);
        namaDokter.setText(b);
        tempatDokter.setText(c);
        tanggalDokter.setDate(java.sql.Date.valueOf(d));
        jkDokter.setSelectedItem(e);
        agamaDokter.setSelectedItem(f);
        spesialisDokter.setSelectedItem(g);
        telpDokter.setText(h);
        
    }//GEN-LAST:event_tDokterMouseClicked

    private void idDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idDokterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idDokterActionPerformed

    /**zl
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dataDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dataDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dataDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dataDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dataDokter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> agamaDokter;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JTextField idDokter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jkDokter;
    private javax.swing.JTextField namaDokter;
    private javax.swing.JButton reset;
    private javax.swing.JButton save;
    private javax.swing.JComboBox<String> spesialisDokter;
    private javax.swing.JTable tDokter;
    private com.toedter.calendar.JDateChooser tanggalDokter;
    private javax.swing.JTextField telpDokter;
    private javax.swing.JTextField tempatDokter;
    // End of variables declaration//GEN-END:variables
}
