package vp;

import helper.database;
import helper.reset;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author FADIL
 */
public class Obat extends javax.swing.JFrame {
    private Connection conn = new helper.database().connect();
    database db = new database();
    private DefaultTableModel tabmode;
    reset rst = new reset();
    String table = "obat";
    String[] columns = {"id_obat","nama_obat","harga","jenis_obat","expired","stock"};
    String[] columnsUpdate = {"nama_obat","harga","jenis_obat","expired","stock"};
    ArrayList<String> selectedValues = new ArrayList<>();
    
    public Obat() {
        initComponents();
        datatable();
        cbTablet.addActionListener(e -> {
        if (cbTablet.isSelected()) {
                selectedValues.add(cbTablet.getText());
            } else {
                selectedValues.remove(cbTablet.getText());
            }
        });

        cbSyrup.addActionListener(e -> {
            if (cbSyrup.isSelected()) {
                selectedValues.add(cbSyrup.getText());
            } else {
                selectedValues.remove(cbSyrup.getText());
            }
        });

        cbKaplet.addActionListener(e -> {
            if (cbKaplet.isSelected()) {
                selectedValues.add(cbKaplet.getText());
            } else {
                selectedValues.remove(cbKaplet.getText());
            }
        });
        
        cbPuyer.addActionListener(e -> {
            if (cbPuyer.isSelected()) {
                selectedValues.add(cbPuyer.getText());
            } else {
                selectedValues.remove(cbPuyer.getText());
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tNamaObat = new javax.swing.JTextField();
        tIdObat = new javax.swing.JTextField();
        tHarga = new javax.swing.JTextField();
        tStock = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabObat = new javax.swing.JTable();
        bEdit = new javax.swing.JButton();
        bDelete = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        bSave = new javax.swing.JButton();
        cbTablet = new javax.swing.JCheckBox();
        cbKaplet = new javax.swing.JCheckBox();
        cbSyrup = new javax.swing.JCheckBox();
        cbPuyer = new javax.swing.JCheckBox();
        tExpired = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Nama Obat");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 155, -1, 25));

        jLabel3.setText("ID Obat");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 121, 61, 28));

        jLabel4.setText("Harga");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 192, 61, 24));

        jLabel5.setText("Jenis Obat");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 222, 61, 25));

        jLabel6.setText("Expired");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 272, -1, 25));

        jLabel7.setText("Stock");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 39, 25));

        tNamaObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNamaObatActionPerformed(evt);
            }
        });
        getContentPane().add(tNamaObat, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 152, 340, -1));
        getContentPane().add(tIdObat, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 121, 340, -1));
        getContentPane().add(tHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 186, 340, -1));
        getContentPane().add(tStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 210, -1));

        tabObat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nama Obat", "ID Obat", "Harga", "Jenis Obat", "Expired", "Stock"
            }
        ));
        tabObat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabObatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabObat);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 346, 784, 217));

        bEdit.setText("Edit");
        bEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditActionPerformed(evt);
            }
        });
        getContentPane().add(bEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 580, 93, 38));

        bDelete.setText("Delete");
        bDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(bDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 580, 93, 38));

        jButton4.setText("Reset");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 580, 93, 39));

        bSave.setText("Save");
        bSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaveActionPerformed(evt);
            }
        });
        getContentPane().add(bSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 580, 93, 37));

        cbTablet.setText("Tablet");
        cbTablet.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbTabletItemStateChanged(evt);
            }
        });
        cbTablet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTabletActionPerformed(evt);
            }
        });
        getContentPane().add(cbTablet, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 214, -1, -1));

        cbKaplet.setText("Kaplet");
        cbKaplet.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbKapletItemStateChanged(evt);
            }
        });
        cbKaplet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKapletActionPerformed(evt);
            }
        });
        getContentPane().add(cbKaplet, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 240, -1, -1));

        cbSyrup.setText("Syrup");
        cbSyrup.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbSyrupItemStateChanged(evt);
            }
        });
        cbSyrup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSyrupActionPerformed(evt);
            }
        });
        getContentPane().add(cbSyrup, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 240, -1, -1));

        cbPuyer.setText("Puyer");
        cbPuyer.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbPuyerItemStateChanged(evt);
            }
        });
        cbPuyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPuyerActionPerformed(evt);
            }
        });
        getContentPane().add(cbPuyer, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 214, -1, -1));
        getContentPane().add(tExpired, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 200, -1));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setText("Data Obat");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(442, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(333, 333, 333))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tNamaObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNamaObatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNamaObatActionPerformed
    
    void reset(){
        rst.resetTextFields(this.getContentPane());
    }
    
    protected void datatable(){
        Object[] Baris = {"id_obat","nama_obat","harga","jenis_obat","expired","stock"};
        tabmode  = new DefaultTableModel(null, Baris);
        tabObat.setModel(tabmode);
        String sql = "select * from obat";
        try{
            Statement stat = conn.createStatement();
            ResultSet res = stat.executeQuery(sql);
            while(res.next()){
                String a = res.getString("id_obat");
                String b= res.getString("nama_obat");
                String d= res.getString("harga");
                String e = res.getString("jenis_obat");
                String f = res.getString("expired");
                String g = res.getString("stock");
                String[] data = {a,b,d,e,f,g};
                tabmode.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Obat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void bSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveActionPerformed
        String delimiter = ",";
        
        StringBuilder sb = new StringBuilder(); 
        
        for (int i = 0; i < selectedValues.size(); i++) {
            sb.append(selectedValues.get(i));
            
            if (i < selectedValues.size() - 1) {
                sb.append(delimiter);
            }
        }
        
        String nama_obat = tNamaObat.getText();
        String harga = tHarga.getText();
        String jenisObat = sb.toString();
        java.sql.Date expired = new java.sql.Date(tExpired.getDate().getTime());
        String stock = tStock.getText();
        
        Object []values = {"0", nama_obat,harga,jenisObat,expired,stock};
        try{
            db.insertData(conn, table, columns, values);
            datatable();
            reset();
        } catch (SQLException ex) {
            Logger.getLogger(Obat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bSaveActionPerformed

    private void cbTabletItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbTabletItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTabletItemStateChanged

    private void cbTabletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTabletActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTabletActionPerformed

    private void cbKapletItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbKapletItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbKapletItemStateChanged

    private void cbKapletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKapletActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbKapletActionPerformed

    private void cbSyrupItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbSyrupItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSyrupItemStateChanged

    private void cbSyrupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSyrupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSyrupActionPerformed

    private void cbPuyerItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbPuyerItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPuyerItemStateChanged

    private void cbPuyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPuyerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPuyerActionPerformed

    private void bEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditActionPerformed
        String delimiter = ",";
        
        StringBuilder sb = new StringBuilder(); 
        
        for (int i = 0; i < selectedValues.size(); i++) {
            sb.append(selectedValues.get(i));
            
            if (i < selectedValues.size() - 1) {
                sb.append(delimiter);
            }
        }
        String id_obat = tIdObat.getText();
        String nama_obat = tNamaObat.getText();
        String harga = tHarga.getText();
        String jenisObat = sb.toString();
        java.sql.Date expired = new java.sql.Date(tExpired.getDate().getTime());
        String stock = tStock.getText();
        String condition = "id_obat = " + id_obat ;
        
        Object []values = { nama_obat,harga,jenisObat,expired,stock};
        try{
            db.updateData(conn, table, columnsUpdate, values,condition);
            datatable();
            reset();
        } catch (SQLException ex) {
            Logger.getLogger(Obat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bEditActionPerformed

    private void bDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteActionPerformed
        String id_obat = tIdObat.getText();
        try {
            String condition = "id_obat= '" + id_obat + "'";
            db.deleteData(conn, table, condition);
            datatable();
            reset();
        } catch (SQLException ex) {
            Logger.getLogger(Obat.class.getName()).log(Level.SEVERE, null, ex);
            
        }
    }//GEN-LAST:event_bDeleteActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        reset();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tabObatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabObatMouseClicked
        int selectedRowIndex =  tabObat.getSelectedRow();
        String a = tabmode.getValueAt(selectedRowIndex, 0).toString();
        String b = tabmode.getValueAt(selectedRowIndex, 1).toString();
        String c = tabmode.getValueAt(selectedRowIndex, 2).toString();
//        String d = tabmode.getValueAt(selectedRowIndex, 3).toString();
        String e = tabmode.getValueAt(selectedRowIndex, 4).toString();
//        String f = tabmode.getValueAt(selectedRowIndex, 5).toString();
        String f = tabmode.getValueAt(selectedRowIndex, 5).toString();
        
        tIdObat.setText(a);
        tNamaObat.setText(b);
        tHarga.setText(c);
//        tKeluhan.setText(d);
        tExpired.setDate(java.sql.Date.valueOf(e));
        tStock.setText(f);
    }//GEN-LAST:event_tabObatMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])  {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Obat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bDelete;
    private javax.swing.JButton bEdit;
    private javax.swing.JButton bSave;
    private javax.swing.JCheckBox cbKaplet;
    private javax.swing.JCheckBox cbPuyer;
    private javax.swing.JCheckBox cbSyrup;
    private javax.swing.JCheckBox cbTablet;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser tExpired;
    private javax.swing.JTextField tHarga;
    private javax.swing.JTextField tIdObat;
    private javax.swing.JTextField tNamaObat;
    private javax.swing.JTextField tStock;
    private javax.swing.JTable tabObat;
    // End of variables declaration//GEN-END:variables
}
